### PR TITLE
csv module expects byte input. pre-encode everything

### PR DESCRIPTION
**Pull request by stefanor**

### CODE REVIEW

**Comment by drnlm** [comment]
I'm pretty sure this is not true for python 3's csv module, so I don't think this will do the right thing when run with python 3.

**Comment by hodgestar** [comment]
I think this PR might be fixing things in the wrong place. I'm guessing this has nothing to do with encodings and is rather to do with `FormRegisteredUserList.details` returning crazy things instead of a list of unicode strings?

(I don't know exactly what broke though, so I could easily be wrong).

**Comment by stefanor** [comment]
@drnlm: Hrm, that's an issue. We could just yield item under python3...

@hodgestar: See the big fat note on https://docs.python.org/2/library/csv.html
We are getting unicode strings, and then trying to encode them to ascii, which doesn't work :)

**Comment by drnlm** [comment]
Just  yielding under python 3 seems a reason approach.

**Comment by stefanor** [comment]
Here is a far simpler approach, that works under Python2 and 3.

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
