### PR TITLE
Pass query string when redirecting to page views.

### PR DESCRIPTION
**Pull request by hodgestar**
Addresses #102.

### CODE REVIEW

**Comment by hodgestar** [comment]
We should probably add tests.

**Comment by drnlm** [comment]
This test case correctly fails on master and passes with Django 1.7 on the fixed branch for me.

It fails on Django 1.8 for me due to what looks like a Django 1.8 change - I haven't investigated how to fix that correctly yet.

**Comment by drnlm** [comment]
Passes with Django 1.8 when #111 is merged into the mix.

**Comment by hodgestar** [comment]
:+1: once #111 is merged in an Travis builds pass.

**Pull request merged**
