### PR TITLE
Truncate long ticket types and add tests.

### PR DESCRIPTION
**Pull request by hodgestar**
Addresses #103.

### CODE REVIEW

**Comment by hodgestar** [comment]
Ready for review.

**Comment by drnlm** [comment]
We only show the type in the admin interface and related management queries, right? If that's true, not logging is fine - it was mainly a thought for helping identify the cause of truncated tickets.

Increasing the size of the field does seems a good idea for the future.

**Comment by hodgestar** [comment]
TicketType.name length increased to 255 characters. Ready for re-review.

**Comment by drnlm** [comment]
Looks fine to me

:+1:

**Pull request merged**
