### PR TITLE
nav: allow redefining background style

### PR DESCRIPTION
**Pull request by terceiro**

### CODE REVIEW

**Comment by hodgestar** [comment]
Is the existing class `navbar` not sufficient for styling?

**Comment by drnlm** [comment]
Given that bootstrap is moving away from direct theme specification (navbar-light has been deprecated, navbar-dark has been reworked), we should probably update to current bootstrap and remove some of the hard-coded theme choices rather than mess around too much with adding extra customisation that isn't going to be useful long term.

**Comment by stefanor** [comment]
I wonder if this can just be handled in some SCSS?

**Comment by terceiro** [comment]
yeah it can probably be handled in some other way, but it would laso be nice if the template didn't hardcode navbar-dark bg-dark (which will force me to undo/revert all the styling done by those classes)

**Comment by stefanor** [comment]
Yes, defaulting to dark is probably not useful for customizing

**Pull request closed without merging**
