### PR TITLE
Sparse schedule support

### PR DESCRIPTION
**Pull request by stefanor**
If you want a schedule item to span an entire row, it must be the only
thing in the row, and have the "expand" css_class.

### CODE REVIEW

**Comment by stefanor** [comment]
The DebConf16 schedule is rather sparse, and thus a little misleading.

Before:
before

After:
after

**Comment by drnlm** [comment]
"The only item in a row" is not a restriction we should require. It breaks use cases with venues that may be split or combined. Scheduling a talk in the combined venue while a tutorial is running in parallel is hardly an uncommon use case, and one we still want to support.

**Comment by stefanor** [comment]
> Scheduling a talk in the combined venue while a tutorial is running in parallel is hardly an uncommon use case, and one we still want to support.

I don't think this is really the right mechanism for that. Currently, it expands to fill all available space.

I can remove the "only thing in the row" restriction, but it'll still just be expanding as far as possible. Quite likely into rooms that are irrelevant.

**Comment by drnlm** [comment]
a) This shouldn't break the test suite.

b) This shouldn't be shoved into css_class - this is completely unrelated to that's intended use case.

**Comment by stefanor** [comment]
> This shouldn't break the test suite.

Missed that because of the unrelated breakage.

> This shouldn't be shoved into css_class - this is completely unrelated to that's intended use case.

Not completely, it's a mostly visual thing. The event is still tied to a specific venue, under the hood.

**Comment by drnlm** [comment]
You probably want to hookup expand as changeable on the list admin view, but that's not urgent.

:+1:

**Pull request merged**
