### PR TITLE
Merge migrations of #189 and #190

### PR DESCRIPTION
**Pull request by madduck**
These two pull requests create leaf nodes which are merged herein.

Signed-off-by: martin f. krafft <madduck@madduck.net>

### CODE REVIEW

**Comment by hodgestar** [comment]
Oh, I see that this doesn't actually replace #189 and #190. Merging like this is not a good idea though. There should either just be one migration or we should number the migrations `3` and `4` instead of `3` and `3`.

Do you want to do that and re-ping this for review when that's done?

**Comment by madduck** [comment]
Right. So let's be pragmatic and either make #190 depend on #189 (linearising), or merge the two unrelated changes into one changeset. Which would you prefer?

(I deliberately kept them separate, but if you would prefer such pull requests to be linearised right away in the future, I can certainly do that)

**Comment by hodgestar** [comment]
Happy with any of the linearising options. Perhaps one pull request is
easiest?

**Comment by madduck** [comment]
@hodgestar, might I suggest that you merge #189 and then I push an updated #190 and we close #191 (herewith done)?

**Comment by hodgestar** [comment]
Sounds good.

**Pull request closed without merging**
