### PR TITLE
Add Django 1.8 support.

### PR DESCRIPTION
**Pull request by hodgestar**
Starts to address #104.

### CODE REVIEW

**Comment by drnlm** [comment]
:+1:

**Comment by hodgestar** [comment]
I think there are still some templates that need `{% load i18n %}` added.

**Comment by drnlm** [comment]
That's almost certainly the case, although I don't think that prevents merging this.

We should extend the test suite so we touch each template we provide anyway, which should help catch these, but that should be a separate thing from the Django 1.8 work.

**Comment by hodgestar** [comment]
The issue at the moment is that deploying this will break whenever a
template that doesn't have the `{% load i18n %}` is loaded.

**Comment by drnlm** [comment]
I've added enough load tags that static site generation works, which cover all the major parts of the site.

**Comment by hodgestar** [comment]
Thanks!

:+1:

**Pull request merged**
