### PR TITLE
Add video flag to venues

### PR DESCRIPTION
**Pull request by stefanor**
It's quite possible that not all venues have video coverage. DebConf and PyCon ZA are both examples of this.

DebConf has done hacks like `id <= 3` and `description.contains("has video coverage")` in the past, but actually modelling this data would be a better solution.

### CODE REVIEW

**Comment by hodgestar** [comment]
How are other exceptional cases handled -- e.g. video is down in a venue one morning? And how does the video tooling access this? Via the API?

**Comment by drnlm** [comment]
See #384 for some prior discussion about the same issue.

Venue feels like the wrong level of granuality for this, since a venue can easily span multiple days, but not have video for all of them (or all sessions in a single venue on a single day).

**Comment by stefanor** [comment]
> How are other exceptional cases handled -- e.g. video is down in a venue one morning?

We handle this on a talk by talk basis. The content team unsets the video request flag on talks that are not going to be videoed (usually because they're being last-minute scheduled, and the video team can't guarantee the room will be staffed).

> And how does the video tooling access this?

We're actually using it in our templates, e.g. https://debconf18.debconf.org/schedule

https://salsa.debian.org/debconf-team/public/websites/dc18/blob/master/templates/wafer.schedule/schedule_item.html#L12

And the volunteer system hooks into it:
https://salsa.debian.org/debconf-team/public/websites/dc18/blob/master/volunteers/forms.py#L198

> See #384 for some prior discussion about the same issue.

Oh, right, thanks for reminding me of that. Yes, separating video requests from granting video would probably also be useful.

> Venue feels like the wrong level of granuality for this, since a venue can easily span multiple days, but not have video for all of them (or all sessions in a single venue on a single day).

This is true. At DC14, we moved equipment between rooms occasionally (for special events, basically). But this is vary rare because of the set-up time involved.

So, yes, having a video flag on slot is probably more technically correct than on venue. But you'd probably want to seed its value with a value from the venue, because they'd almost always match.

**Comment by hodgestar** [comment]
Could we update the help text to explicitly mention that the flag indicates that items scheduled in this venue will default to being videoed?

I think I'm okay with this landing. I agree that tags provide a much more flexible solution (and I don't think we should abandon that idea), but I'm also wary of creating something too generic for core features (and being videoed seems like a very common feature of conference talks these days).

**Comment by stefanor** [comment]
> We should revisit this after PyConZA, though.

OK.

**Pull request merged**
