### PR TITLE
Bugs/issue 436 return 403 for all profiles

### PR DESCRIPTION
**Pull request by drnlm**
Hopefully addresses #436 

This should return 403 for all user related urls when WAFER_PUBLIC_ATTENDEE_LIST is False and the user isn't logged in.

We are probably too aggressive about returning 404's when WAFER_PUBLIC_ATTENDEE_LIST is True, (see the tests) but I haven't thought through all the implications of changing the behaviour.

### CODE REVIEW

**Comment by drnlm** [comment]
Any opinions on this at all?

**Comment by hodgestar** [comment]
I liked @stefanor's suggestion to link to the login / profile redirect page instead (https://github.com/CTPUG/wafer/issues/436#issuecomment-408578538).

Redirecting to a login page with a 403 makes sense for users who are logged out, but returning a 403 for pages that don't exist to people who are logged in seems odd. The previous logic of returning 404s seems better, and I'm happy for people who turn on WAFER_PUBLIC_ATTENDEE_LIST to have to think a bit about which pages they link to in emails.

The new tests are great, so it would be good to keep those if we can.

**Comment by drnlm** [comment]
> I liked @stefanor's suggestion to link to the login / profile redirect page instead ([#436 (comment)](https://github.com/CTPUG/wafer/issues/436#issuecomment-408578538)).

This is far from the only way a user can try access their profile while being logged out, and many of them, such as bookmarks or browser history, are outside the control of the conference.

> Redirecting to a login page with a 403 makes sense for users who are logged out, but returning a 403 for pages that don't exist to people who are logged in seems odd. 
>The previous logic of returning 404s seems better, and I'm happy for people who turn on WAFER_PUBLIC_ATTENDEE_LIST to have to think a bit about which pages they link to in emails.

Did you mean "turn off WAFER_PUBLIC_ATTENDEE_LIST" ? This doesn't change the behaviour for the public list case.

With a private user list, we will deny access to users who are logged in all the time - there is a lot of things non-admin users are not allowed to do (edit other people's profiles, see users without talks, etc).  The issue is that we don't want to allow any sort of enumeration of users based on error code, so we collapse both 404's and 403's into the same error message, regardless of the user's logged in state. Collapsing everything into 404's leads to the complaints we see in #436. I fail to see a compelling reason why returning 404 to a logged in user for an existing page is a better choice  than returning 403 for a non-existent page and contend that collapsing everything to 403 is going to create a better user experience.

There is an argument that we should have different behaviour when the user is an admin, since they can already enumerate the user list via the admin site, and returning 403 instead of 404 is misleading, but that is a future enhancement.

**Comment by hodgestar** [comment]
After reading @drnlm's comment and thinking through this a bit more, I'm happy with this! During my thinking and trying things out, I realized wafer doesn't have a custom 403.html template, so we should add that (in a separate PR probably).

**Pull request merged**
