### PR TITLE
wafer.setting: log errors to the console

### PR DESCRIPTION
**Pull request by terceiro**
I'm trying to debug problems with sending email. In this case, the only logging
available being sending email is ... suboptimal. :-)

### CODE REVIEW

**Comment by stefanor** [comment]
Is that really a default we want? I wouldn't want this in production.

**Comment by hodgestar** [comment]
I think there are three roles this setting can play:
1. Production default
2. Development default
3. Documentation (i.e. an example of how to set up logging)
Currently in practice it is used as 1 by PyConZA. I think this PR helps 2 at the expense of 1. Any ideas on how to fulfill all three better?

**Comment by drnlm** [comment]
Given that we advise people to build an app around wafer, we should consider dropping the default logging section from settings.py entirely, and move the comment to the docs, and add explicit instructions that users should setup their own logging configuration. Maybe also suggesting some common choices?

**Comment by terceiro** [comment]
IMO logging errors to stderr is a reasonable default, even for production. If you are running under apache/mod_wsgi, those get to the apache error log. If you are running e.g. gunicorn in a docker/"cloud native" environment, that's how you are supposed to do logging in the first place.

In general I think it's useful to provide as many sensible defaults as possible, to reduce the amount of boilerplate one has to add to apps using wafer. And, those who have strong opinions about those settings can already easily override them.

**Comment by stefanor** [comment]
Fair enough

**Comment by drnlm** [comment]
There isnt going to be a universally good default, and having too many options enabled by default is also a bad idea. I'm not particulatly convinced that wafer should actually be providing an enabled logging method by default, but having both mail and logging to stderr enabled doesn't seem generally useful.

Also, whatever we have enabled should be discussed in the documentation, and updating / changing the logging setup should be discussed in the installation document.

**Pull request closed without merging**
