### PR TITLE
Improve the 'no talks submitted' display for talks and speakers

### PR DESCRIPTION
**Pull request by drnlm**
The current 'No talks accepted' pages are missing bits or blank - this adds a bit more theming so they hopefully look less ugly.

### CODE REVIEW

**Review by hodgestar — APPROVED** [review]
Looks good to me.

I see some tests failed. Not sure if it's related yet.

**Comment by hodgestar** [comment]
I see there is lots of `django.template.exceptions.TemplateDoesNotExist: bootstrap4/field.html`.

**Comment by drnlm** [comment]
> I see there is lots of `django.template.exceptions.TemplateDoesNotExist: bootstrap4/field.html`.

We either need to restrict crispy-forms to an old version, add cripsy_boostrap4 as a depedncy (although there are questions about how long this will be supported given that bootstrap has reach end of life) or merge #651 for bootstrap5 support.

**Comment by hodgestar** [comment]
I would say let's move forwards to bootstrap5. #651 approved.

**Pull request merged**
